//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kynapsis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kynapsisEntities1 : DbContext
    {
        public kynapsisEntities1()
            : base("name=kynapsisEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividades_Especiales> Actividades_Especiales { get; set; }
        public virtual DbSet<CitaGrupal> CitaGrupal { get; set; }
        public virtual DbSet<CitaIndividual> CitaIndividual { get; set; }
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<Fisioterapeuta> Fisioterapeuta { get; set; }
        public virtual DbSet<FisioterapeutaActividadesEspeciales> FisioterapeutaActividadesEspeciales { get; set; }
        public virtual DbSet<HorarioFisioterapeuta> HorarioFisioterapeuta { get; set; }
        public virtual DbSet<Orden> Orden { get; set; }
        public virtual DbSet<OrdenCitasGrupales> OrdenCitasGrupales { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
    }
}
